spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT_DUMMY}/somojeon?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: ${RDS_ID}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: ${ADMIN_MAIL}
oauth:
  kakao:
    redirect-address: http://localhost:8080/login/oauth2/code/kakao
#    redirect-address: https://dev.somojeon.site/login/oauth2/code/kakao

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error